spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fintechdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # auto-create tables based on Entities
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080